### ISSUE TITLE
Website doesn't show correct information

### ISSUE THREAD

**Issue by Amet13** [matopeto/kindle-weather-dashboard#23]
About a week ago (probably after this commit: https://github.com/matopeto/kindle-weather-dashboard/commit/58320a313be2eaf0708a54ba126a47208d867dd0) the website stopped working on my Kindle.

The website works from my mobile/laptop browser, however it doesn't work on Kindle.
![IMG_3137](https://github.com/matopeto/kindle-weather-dashboard/assets/5184847/337d049c-6141-40df-bafe-8b26eb2af83a)

Any chance that I do something wrong? It worked perfectly till the last week.

Kindle 5, 2012

**Comment by matopeto** [comment]
Hi.

Thanks for the report. 

I will look at this next week

(but i tested on my kindle 5 and it works ok)

Can you try go to config from Kindle and setup it again?

http://kindle.hrincar.eu/weather/config.html

**Comment by Amet13** [comment]
Yes, I tried to check that from Kindle couple of times but it's still doesn't work.

**Comment by matopeto** [comment]
Ok. I will try to fix it next week or i will provide you an url with deployed an old version

**Comment by matopeto** [comment]
Hi @Amet13 

"It's works on my machine" :)

1. what firmware your kindle have? (Go to settings and in the footer is version (mine is 4.1.1 (1813939925))
2. can you confirm that you dont have javascript disabled in kindle browser?
3. Can you please send me a screens of of your config, and all you have set? So i can try to replicate your settings
4. I deployed old version to http://kindle.hrincar.eu/weather-old/config.html  "`weather-old`" instead of "`weather`", can you please confirm that old version works for you

**Comment by Amet13** [comment]
Hi @matopeto ,
I'm on vacation now, will come back on Sat.
Could you please keep the old version for a week until I check it at home? Thanks

**Comment by matopeto** [comment]
Yes, it will be deployed until we resolve this issue :)

**Comment by Amet13** [comment]
Thank you for keeping the old version of website.
I was able to test it from Kindle, unfortunately, it also didn't work for me, so I made a conclusion that something wrong on my side.
I reset Kindle to factory settings and tried to access new version of website and it works. I have no idea what was wrong but it helped.
Sorry for bothering, I'm closing this issue.
