### ISSUE TITLE
Wanted 4/5-day forecast as opposed to 4-5 daily forecasts

### ISSUE THREAD

**Issue by darryllee** [matopeto/kindle-weather-dashboard#30]
Hi - this isn't an issue so much as an offering of my hack of your project.

I don't have the sophistication to code this as a separate option, but I know how to search and replace. So I used the One Call 3.0 API from OpenWeather (warning: requires Credit Card), and made the least amount of tweaks to get it to work.

https://github.com/darryllee/kindle-weather-dashboard/

Obviously I'm not going to do a pull request since it totally breaks the daily forecasts. But in case anybody is looking for longer-term weather forecasts, or heck, if somebody was ambitious/skilled enough to take my changes and make it into a proper option, that'd be cool tool.

Thanks so much for giving one more of my old Kindles a new purpose in life!

**Comment by matopeto** [comment]
@darryllee Thanks for sharing:

I did that in the branch. See comment https://github.com/matopeto/kindle-weather-dashboard/issues/28#issuecomment-2436180695  or Issue #28 

And "Daily Forecast 16 Days" is still free od 2.5 API :)

But I don't trust weather forecasts for more than a few hours :), and since I'm primarily making the project for myself, and it's hard to maintain something universal, I ultimately didn't merge it. However, maybe someday, when I have the time and motivation again, I'll add it somehow.

If you don’t mind, I’ll close this issue, and hopefully people will find it in the closed issues, where they can navigate to your fork or my branch.

**Comment by matopeto** [comment]
Now implemented in main branch and deployed to my page
